name=SR Hardware
version=1.0.0
author=Shreyas Rangadhol
maintainer=Shreyas Rangadhol
sentence=Reusable hardware modules for ESP32 and Arduino projects.
paragraph=A personal hardware library containing reusable modules for robotics, IoT, sensors, controllers, and automation projects.
category=Device Control
url=
architectures=*